### ISSUE TITLE
definition dynamic constraints

### ISSUE THREAD

**Issue by gilserrancoli** [antoinefalisse/ISB21-workshop#1]
https://github.com/antoinefalisse/ISB21-workshop/blob/96197af72e0fa93a0796174d56fcabbd8224ded4/MATLAB/main.m#L254

Instead of dq - dqdt = 0, would it be better: dqdt*=dqdt?
and instead of ddq - ddqdt = 0, would it be: ddqdt*=ddqdt?
being dqdt* and ddqdt* the first and second derivative of the coordinate calculated by using coordinate and velocity values, and dqdt and ddqdt being the design variables corresponding to the first and second derivatives.

**Comment by antoinefalisse** [comment]
Thanks @gilserrancoli. Updated now: https://github.com/antoinefalisse/ISB21-workshop/blob/main/MATLAB/main.m#L277
